<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Royal Garam Masala',
                'sku' => 'FF-GM-100',
                'category' => 'Signature blend',
                'unit' => '100 g',
                'description' => 'A warm, layered masala built for curries, gravies, biryani, and everyday home cooking.',
                'long_description' => 'Royal Garam Masala is a fragrant finishing blend designed to add warmth without overpowering the food. Whole spices are balanced for a rounded aroma that works across rich gravies, biryani, dals, and simple weekday sabzi.',
                'highlights' => [
                    'Slow-roasted whole-spice aroma',
                    'No artificial colours or fillers',
                    'Works as a cooking and finishing masala',
                ],
                'ingredients' => 'Coriander, cumin, black pepper, cinnamon, cloves, cardamom, bay leaf, and nutmeg.',
                'usage_instructions' => 'Add 1/2 to 1 teaspoon near the end of cooking. Adjust to taste and seal the pack after use.',
                'origin' => 'Blended and packed in Gujarat, India',
                'badge' => 'Hero pick',
                'price' => 149,
                'compare_at_price' => 179,
                'quantity' => 120,
                'low_stock_threshold' => 15,
                'rating' => 4.9,
                'priority' => 95,
                'image_path' => 'images/flavourflow-mark.png',
                'is_featured' => true,
            ],
            [
                'name' => 'Red Chilli Powder',
                'sku' => 'FF-RC-100',
                'category' => 'Pure spice',
                'unit' => '100 g',
                'description' => 'Bright colour, clean heat, and a bold finish for daily recipes.',
                'long_description' => 'A vivid red chilli powder selected for clean heat and bright natural colour. It lifts tadka, curries, marinades, and snacks while keeping the flavour direct and dependable.',
                'highlights' => [
                    'Bright natural colour',
                    'Clean, balanced heat',
                    'Finely milled for even mixing',
                ],
                'ingredients' => '100% dried red chillies.',
                'usage_instructions' => 'Use 1/4 to 1 teaspoon depending on the heat level you prefer. Store in a cool, dry place.',
                'origin' => 'Sourced and packed in India',
                'badge' => 'Best seller',
                'price' => 99,
                'compare_at_price' => 119,
                'quantity' => 86,
                'low_stock_threshold' => 12,
                'rating' => 4.8,
                'priority' => 88,
                'image_path' => 'images/flavourflow-spice-hero.png',
                'is_featured' => false,
            ],
            [
                'name' => 'Kitchen King Mix',
                'sku' => 'FF-KK-100',
                'category' => 'Everyday blend',
                'unit' => '100 g',
                'description' => 'A balanced spice profile for sabzi, snacks, and quick family meals.',
                'long_description' => 'Kitchen King Mix brings savoury depth to the dishes that appear most often on the family table. Its balanced profile makes it an easy single-blend choice for vegetables, paneer, pulao, and quick snacks.',
                'highlights' => [
                    'One blend for everyday recipes',
                    'Balanced savoury aroma',
                    'Ideal for vegetables, paneer, and rice',
                ],
                'ingredients' => 'Coriander, cumin, turmeric, chilli, black pepper, dried ginger, fenugreek, and aromatic spices.',
                'usage_instructions' => 'Add 1 to 2 teaspoons while cooking for four servings. Fry briefly with the masala base for the best aroma.',
                'origin' => 'Blended and packed in Gujarat, India',
                'badge' => 'Popular',
                'price' => 129,
                'compare_at_price' => 149,
                'quantity' => 48,
                'low_stock_threshold' => 10,
                'rating' => 4.7,
                'priority' => 82,
                'image_path' => 'images/flavourflow-hero.png',
                'is_featured' => false,
            ],
            [
                'name' => 'Golden Turmeric Powder',
                'sku' => 'FF-TU-100',
                'category' => 'Pure spice',
                'unit' => '100 g',
                'description' => 'Earthy, golden turmeric for vibrant curries, dals, and nourishing everyday meals.',
                'long_description' => 'Golden Turmeric Powder is finely milled for smooth blending and a rich, natural colour. Its warm, earthy profile makes it a reliable pantry essential for tadkas, curries, soups, marinades, and traditional home remedies.',
                'highlights' => [
                    'Deep natural golden colour',
                    'Finely milled for smooth blending',
                    'A pantry staple for everyday cooking',
                ],
                'ingredients' => '100% ground turmeric.',
                'usage_instructions' => 'Add 1/4 to 1/2 teaspoon while cooking. Fry briefly with oil or ghee to release its aroma and colour.',
                'origin' => 'Sourced and packed in India',
                'badge' => 'Everyday essential',
                'price' => 89,
                'compare_at_price' => 109,
                'quantity' => 94,
                'low_stock_threshold' => 12,
                'rating' => 4.8,
                'priority' => 78,
                'image_path' => 'images/flavourflow-spice-hero.png',
                'is_featured' => false,
            ],
            [
                'name' => 'Cumin Seed Select',
                'sku' => 'FF-CU-100',
                'category' => 'Whole spice',
                'unit' => '100 g',
                'description' => 'Aromatic whole cumin seeds with a warm, nutty flavour for tadkas, rice, and masalas.',
                'long_description' => 'Cumin Seed Select is chosen for its clean aroma and even size. Toast it whole for fragrant tempering, grind it fresh for masalas, or add it to rice dishes, chaats, and marinades for a familiar savoury warmth.',
                'highlights' => [
                    'Fresh, nutty whole-seed aroma',
                    'Ideal for tempering and dry roasting',
                    'Selected for even quality and flavour',
                ],
                'ingredients' => '100% whole cumin seeds.',
                'usage_instructions' => 'Temper 1/2 teaspoon in hot oil or dry-roast before grinding. Store airtight to preserve aroma.',
                'origin' => 'Sourced and packed in Gujarat, India',
                'badge' => 'Fresh batch',
                'price' => 119,
                'compare_at_price' => 139,
                'quantity' => 63,
                'low_stock_threshold' => 10,
                'rating' => 4.7,
                'priority' => 74,
                'image_path' => 'images/flavourflow-mark.png',
                'is_featured' => false,
            ],
            [
                'name' => 'Coriander Powder',
                'sku' => 'FF-CO-100',
                'category' => 'Pure spice',
                'unit' => '100 g',
                'description' => 'Fragrant coriander powder with a gentle citrus note for curries, chutneys, and marinades.',
                'long_description' => 'Coriander Powder adds a mellow, rounded base to everyday Indian cooking. Freshly milled coriander seeds bring a subtle citrus aroma that complements vegetable curries, lentils, chaat masala, and grilled marinades.',
                'highlights' => [
                    'Mellow flavour with citrusy aroma',
                    'Freshly milled coriander seeds',
                    'Versatile for curries, chutneys, and marinades',
                ],
                'ingredients' => '100% ground coriander seeds.',
                'usage_instructions' => 'Add 1 to 2 teaspoons with other ground spices while cooking. Use more for a fuller coriander flavour.',
                'origin' => 'Sourced and packed in India',
                'badge' => 'Kitchen staple',
                'price' => 79,
                'compare_at_price' => 99,
                'quantity' => 72,
                'low_stock_threshold' => 10,
                'rating' => 4.6,
                'priority' => 70,
                'image_path' => 'images/flavourflow-hero.png',
                'is_featured' => false,
            ],
            [
                'name' => 'Tandoori Marinade Masala',
                'sku' => 'FF-TM-100',
                'category' => 'Speciality blend',
                'unit' => '100 g',
                'description' => 'A smoky, tangy blend for tandoori-style paneer, vegetables, chicken, and kebabs.',
                'long_description' => 'Tandoori Marinade Masala brings together warming spices, tangy notes, and gentle heat for restaurant-style grilling at home. Mix it with yoghurt, lemon, and oil to create a richly seasoned coating for paneer, vegetables, chicken, or seafood.',
                'highlights' => [
                    'Smoky, tangy tandoori-style profile',
                    'Easy yoghurt-based marinades',
                    'Great for oven, grill, or air fryer',
                ],
                'ingredients' => 'Coriander, cumin, Kashmiri chilli, ginger, garlic, black pepper, paprika, mango powder, fenugreek, and aromatic spices.',
                'usage_instructions' => 'Mix 2 teaspoons with 1/2 cup yoghurt, lemon juice, and oil. Marinate for at least 30 minutes before cooking.',
                'origin' => 'Blended and packed in Gujarat, India',
                'badge' => 'Weekend favourite',
                'price' => 159,
                'compare_at_price' => 189,
                'quantity' => 38,
                'low_stock_threshold' => 8,
                'rating' => 4.9,
                'priority' => 84,
                'image_path' => 'images/flavourflow-offers-composite.png',
                'is_featured' => false,
            ],
            [
                'name' => 'Chaat Masala Zing',
                'sku' => 'FF-CH-100',
                'category' => 'Finishing blend',
                'unit' => '100 g',
                'description' => 'A lively sweet-sour finishing masala for fruit, snacks, salads, and street-style chaat.',
                'long_description' => 'Chaat Masala Zing adds instant brightness to the dishes that need a final lift. Its tangy, savoury flavour is delicious over fruit, roasted vegetables, fries, raita, sandwiches, and homemade chaat.',
                'highlights' => [
                    'Tangy, sweet-sour finishing flavour',
                    'Sprinkle-and-serve convenience',
                    'Perfect for snacks, fruit, and chaat',
                ],
                'ingredients' => 'Mango powder, cumin, black salt, coriander, dried ginger, chilli, black pepper, asafoetida, and aromatic spices.',
                'usage_instructions' => 'Sprinkle 1/4 to 1/2 teaspoon just before serving. Do not overcook; use as a finishing masala.',
                'origin' => 'Blended and packed in Gujarat, India',
                'badge' => 'Snack time',
                'price' => 109,
                'compare_at_price' => 129,
                'quantity' => 56,
                'low_stock_threshold' => 10,
                'rating' => 4.8,
                'priority' => 76,
                'image_path' => 'images/flavourflow-mark.png',
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::query()->updateOrCreate(
                ['slug' => Str::slug($product['name'])],
                [...$product, 'is_active' => true],
            );
        }
    }
}
