<?php

return [
    'meta' => [
        'title' => 'FlavourFlow - Pure Indian Spices',
        'description' => 'Fresh, small-batch Indian spices and balanced blends for everyday cooking.',
    ],

    'brand' => [
        'name' => 'FlavourFlow',
        'tagline' => 'Pure spices. Pure love.',
        'logo' => 'images/flavourflow-mark.png',
    ],

    'navigation' => [
        ['label' => 'Home', 'href' => '#top'],
        ['label' => 'Products', 'href' => '#products'],
    ],

    'hero' => [
        'eyebrow' => 'Small-batch Indian spices',
        'title' => 'FlavourFlow',
        'subtitle' => 'Turn everyday cooking into something unforgettable.',
        'description' => 'Bold aroma, honest ingredients, and balanced blends made to bring depth to every plate.',
        'image' => 'images/flavourflow-spice-hero.png',
        'primary_action' => ['label' => 'Explore the collection', 'href' => '#products'],
        'secondary_action' => ['label' => 'View best sellers', 'href' => '#products'],
        'proof_points' => [
            ['value' => '100%', 'label' => 'Pure ingredients'],
            ['value' => '4.9', 'label' => 'Community rating'],
            ['value' => 'Fresh', 'label' => 'Small-batch packed'],
        ],
    ],

    'products' => [
        [
            'name' => 'Royal Garam Masala',
            'category' => 'Signature blend',
            'description' => 'A warm, layered masala built for curries, gravies, biryani, and everyday home cooking.',
            'badge' => 'Hero pick',
            'price' => 'From Rs. 149',
            'compare_at_price' => 'Rs. 179.00',
            'metric' => '4.9 rating',
            'image' => 'images/flavourflow-mark.png',
            'sku' => 'FF-GM-100',
            'unit' => '100 g',
            'quantity' => 120,
            'stock_label' => 'In stock',
            'in_stock' => true,
            'is_featured' => true,
            'is_active' => true,
            'priority' => 95,
            'rating' => 4.9,
        ],
        [
            'name' => 'Red Chilli Powder',
            'category' => 'Pure spice',
            'description' => 'Bright colour, clean heat, and a bold finish for daily recipes.',
            'badge' => 'Best seller',
            'price' => 'From Rs. 99',
            'compare_at_price' => 'Rs. 119.00',
            'metric' => 'High demand',
            'image' => 'images/flavourflow-hero.png',
            'sku' => 'FF-RC-100',
            'unit' => '100 g',
            'quantity' => 86,
            'stock_label' => 'In stock',
            'in_stock' => true,
            'is_featured' => false,
            'is_active' => true,
            'priority' => 88,
            'rating' => 4.8,
        ],
        [
            'name' => 'Kitchen King Mix',
            'category' => 'Everyday blend',
            'description' => 'Balanced spice profile for sabzi, snacks, and quick family meals.',
            'badge' => 'Popular',
            'price' => 'From Rs. 129',
            'compare_at_price' => 'Rs. 149.00',
            'metric' => 'Fast moving',
            'image' => 'images/flavourflow-mark.png',
            'sku' => 'FF-KK-100',
            'unit' => '100 g',
            'quantity' => 48,
            'stock_label' => 'In stock',
            'in_stock' => true,
            'is_featured' => false,
            'is_active' => true,
            'priority' => 82,
            'rating' => 4.7,
        ],
        [
            'name' => 'Turmeric Powder',
            'category' => 'Essential spice',
            'description' => 'Golden colour and earthy aroma for everyday Indian cooking.',
            'badge' => 'Essential',
            'price' => 'From Rs. 79',
            'compare_at_price' => '',
            'metric' => 'Daily use',
            'image' => 'images/flavourflow-mark.png',
            'sku' => 'FF-TP-100',
            'unit' => '100 g',
            'quantity' => 72,
            'stock_label' => 'In stock',
            'in_stock' => true,
            'is_featured' => false,
            'is_active' => true,
            'priority' => 76,
            'rating' => 4.6,
        ],
    ],

    'footer_links' => [
        ['label' => 'Home', 'href' => '#top'],
        ['label' => 'Products', 'href' => '#products'],
    ],
];
